[build]
  command = "npm run build"
  publish = "out"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["next", "require_optional", "typeorm", "app-root-path", "@ampproject/toolbox-optimizer", "sharp"]