import { getSession } from "next-auth/client";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Header from "../components/Header/Header";
import Login from "../components/Login";

export default function Home({ session }) {
  if (!session) {
    return <Login />;
  }
  return (
    <div>
      <Head>
        <title>Social Freaks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return { props: { session } };
}
