import { getSession } from "next-auth/client";
import Head from "next/head";
import styled from "styled-components";
import Feed from "../components/Feed";
import Header from "../components/Header/Header";
import Login from "../components/Login";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";

export default function Home({ session }) {
  if (!session) {
    return <Login />;
  }
  return (
    <Container>
      <Head>
        <title>Social Freaks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <Sidebar />
        <Feed />
        <Widgets />
      </Main>
    </Container>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return { props: { session } };
}

const Container = styled.div`
  overflow: hidden;
  display: flex;
  flex-direction: column;
`;
const Main = styled.div`
  display: flex;
  margin-top: 40px;
  justify-content: space-between;
`;
